# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CICD

on:
  push:
    branches: [ "main", "develop" ]
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
 S3PackageUpload:
    runs-on: ubuntu-latest
    environment:
      name: ${{ (github.ref == 'refs/heads/main') && 'production' || 'develop' }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Environment
        run: |
         echo " ARN: ${{ vars.AWS_ARN }}"
         echo " region: ${{ vars.AWS_REGION }}"
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.AWS_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      # Upload a file to AWS s3
      - name:  List S3
        run: |
          aws s3 ls
